project:
  type: website

website:
  title: "NYC Open Data Stories"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: contributors.qmd
        text: Contributors
      - href: stories.qmd
        text: Stories
      - href: nyc-open-data-week-2026.qmd
        text: NYC Open Data Week 2026

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true

editor: visual