{
  "hash": "eccc4ed032bd2bb8cb3961e68b81f96b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Toxic Homes: Exploring Mold Exposure Complaint and Domestic Violence Report Trends in NYC\"\nauthor: \"Shannon Joyce\"\ndescription: \"This project explores whether residential mold complaints and domestic violence reports in New York City follow similar patterns over time. Using NYC Open Data from 2010 to 2024, the analysis combines monthly borough-level aggregation, correlations, lagged comparisons, and regression models to examine how housing-related environmental stress may align with broader public health and safety trends, while carefully avoiding causal claims.\"\ncategories: [public-health, social-issues, housing]\n---\n\n**Author:** [Shannon Joyce](../contributors/shannon-joyce.qmd)\n\n## Toxic Homes: Exploring Mold Exposure Complaint and Domestic Violence Report Trends in NYC {#sec-shannon}\n\nHousing conditions are an important factor in public health and well-being. Poor residential environments, such as mold exposure, can contribute to physical health problems and increased stress. Domestic violence is also influenced by environmental and social stressors, making housing conditions a relevant area of study.\n\nThis project examines the relationship between residential mold complaints and domestic violence reports in New York City from 2010 to 2024. I am using two datasets from NYC Open Data: [311 Complaint Data](https://data.cityofnewyork.us/Social-Services/311-Service-Requests-from-2010-to-Present/erm2-nwe9/about_data) to extract residential mold complaints and [NYPD Complaint Data Historic](https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i/about_data) to extract domestic violence reports. Using NYC 311 mold complaint data and DV report data, I explore whether these two types of reports follow similar patterns over time. The goal is not to determine causation, but to understand whether mold complaints and DV reports tend to rise and fall together.\n\nThe analysis focuses on monthly aggregated data and includes exploratory summaries, correlation analyses, and regression models. I also explore delayed (or lagged) relationships and mold complaint resolution time to better understand how timing may play a role.\n\n## Loading, Prepping, Cleaning, & Aggregating\n\n### Data Preparation & Cleaning\n\n(@R-tidyverse) (@R-readxl) (@R-ggplot2) (@R-mosaic) (@R-AICcmodavg) (@R-knitr) (@R-arrow) (@R-here)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(ggplot2)\nlibrary(mosaic)\nlibrary(AICcmodavg)\nlibrary(knitr)\nlibrary(arrow)\nlibrary(here)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmold_data <- read_parquet(\n  here(\"data\", \"raw\",\"311_Service_Requests_from_2010_to_Present_20251215.parquet\"))\ndv_data <- read_parquet(\n  here(\"data\", \"raw\",\"NYPD_Complaint_Data_Historic_20251218.parquet\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Create a Lookup Table for the Cities (The \"Max Squeeze\" approach)\n# This replaces the 100-line case_when and is much faster/stable\ncity_lookup <- data.frame(\n  City = c(\"NEW YORK\", \"BROOKLYN\", \"ARVERNE\", \"BRONX\", \"JAMAICA\", \"STATEN ISLAND\", \n           \"SPRINGFIELD GARDENS\", \"FLUSHING\", \"RICHMOND HILL\", \"ASTORIA\", \"HOLLIS\", \n           \"RIDGEWOOD\", \"FOREST HILLS\", \"ELMHURST\", \"MASPETH\", \"SOUTH RICHMOND HILL\", \n           \"JACKSON HEIGHTS\", \"BAYSIDE\", \"FAR ROCKAWAY\", \"SAINT ALBANS\", \"CORONA\", \n           \"WOODSIDE\", \"QUEENS VILLAGE\", \"REGO PARK\", \"ROSEDALE\", \"SUNNYSIDE\", \n           \"OZONE PARK\", \"EAST ELMHURST\", \"MIDDLE VILLAGE\", \"WOODHAVEN\", \n           \"SOUTH OZONE PARK\", \"ROCKAWAY PARK\", \"KEW GARDENS\", \"FRESH MEADOWS\", \n           \"COLLEGE POINT\", \"LONG ISLAND CITY\", \"OAKLAND GARDENS\", \"WHITESTONE\", \n           \"HOWARD BEACH\", \"CAMBRIA HEIGHTS\", \"BELLEROSE\", \"LITTLE NECK\", \n           \"BREEZY POINT\", \"GLEN OAKS\", \"FLORAL PARK\", \"PELHAM\", \"NEW HYDE PARK\", \n           \"QUEENS\", \"MANHATTAN\"),\n  Borough_Mapped = c(\"MANHATTAN\", \"BROOKLYN\", \"QUEENS\", \"BRONX\", \"QUEENS\", \"STATEN ISLAND\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"QUEENS\", \n                     \"QUEENS\", \"QUEENS\", \"QUEENS\", \"BRONX\", \"QUEENS\", \n                     \"QUEENS\", \"MANHATTAN\")\n)\n\n# 2. Process Mold Data\nmold_data_clean <- mold_data %>%\n  # Filter Location Types efficiently\n  filter(`Location Type` %in% c(\"RESIDENTIAL BUILDING\", \"Residential Building\", \"Loft Residence\", \n                                \"Mixed Use Building\", \"Apartment\", \"3+ Family Apartment Building\", \n                                \"1-2 Family Dwelling\", \"1-2 Family Mixed Use Building\", \n                                \"3+ Family Mixed Use Building\", \"Single Room Occupancy (SRO)\")) %>%\n  filter(Descriptor != \"Unsafe Mold Cleanup\") %>%\n  mutate(\n    created_date = as.Date(`Created Date`),\n    closed_date  = as.Date(`Closed Date`),\n    # Force Year to numeric to prevent Join errors\n    Year  = as.numeric(lubridate::year(created_date)),\n    # Clean Month formatting\n    Month = sprintf(\"%02d - %s\", \n                    lubridate::month(created_date), \n                    lubridate::month(created_date, label = TRUE, abbr = FALSE)),\n    resolution_days = as.numeric(closed_date - created_date),\n    `Complaint Type` = case_when(\n      `Complaint Type` %in% c(\"UNSANITARY CONDITION\", \"Unsanitary Condition\", \"MOLD\", \"GENERAL\", \"GENERAL CONSTRUCTION\") ~ \"Mold\",\n      TRUE ~ `Complaint Type`\n    )\n  ) %>%\n  # Use the lookup table for City -> Borough\n  left_join(city_lookup, by = \"City\") %>% \n  mutate(Borough = coalesce(Borough_Mapped, \"UNKNOWN\")) %>%\n  filter(Borough != \"UNKNOWN\", Year != 2025)\n\n# 3. Process DV Data\ndv_data_clean <- dv_data %>% \n  rename(\n    \"complaint_number\" = `CMPLNT_NUM`,\n    \"inc_occur_date\" = `CMPLNT_FR_DT`,\n    \"inc_occur_time\" = `CMPLNT_FR_TM`,\n    \"inc_end_date\" = `CMPLNT_TO_DT`,\n    \"inc_end_time\" = `CMPLNT_TO_TM`,\n    \"precinct_occur\" = `ADDR_PCT_CD`,\n    \"report_date\" = `RPT_DT`,\n    \"key_code\" = `KY_CD`,\n    \"offense_type\" = `OFNS_DESC`,\n    \"class_code\" = `PD_CD`,\n    \"class_code_desc\" = `PD_DESC`,\n    \"attempt_completion\" = `CRM_ATPT_CPTD_CD`,\n    \"offense_level\" = `LAW_CAT_CD`,\n    \"borough\" = `BORO_NM`,\n    \"suspect_age\" = `SUSP_AGE_GROUP`,\n    \"suspect_race\" = `SUSP_RACE`,\n    \"suspect_sex\" = `SUSP_SEX`,\n    \"victim_age\" = `VIC_AGE_GROUP`,\n    \"victim_race\" = `VIC_RACE`,\n    \"victim_sex\" = `VIC_SEX`\n  ) %>%\n  mutate(\n    inc_date_converted = as.Date(inc_occur_date),\n    # Force Year to numeric to match Mold data\n    Year  = as.numeric(lubridate::year(inc_date_converted)),\n    Month = sprintf(\"%02d - %s\", \n                    lubridate::month(inc_date_converted), \n                    lubridate::month(inc_date_converted, label = TRUE, abbr = FALSE)),\n    complaint = \"DV\"\n  ) %>%\n  filter(Year >= 2010 & Year < 2025)\n\nmold_data_clean <- mold_data_clean %>% mutate(Year = as.character(Year))\ndv_data_clean   <- dv_data_clean   %>% mutate(Year = as.character(Year))\n\n# 4. Final memory cleanup (optional but helpful for cloud publishing)\nrm(mold_data, dv_data)\n```\n:::\n\n\n\n::: {#tbl-mold_data_clean .cell}\n\n```{.r .cell-code}\nkable(head(mold_data_clean, 3),\n      caption = \"Preview of cleaned 311 residential mold complaints (first 3 rows) after filtering to residential location types and creating date/resolution fields.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Preview of cleaned 311 residential mold complaints (first 3 rows) after filtering to residential location types and creating date/resolution fields.\n\n|Unique Key |Created Date            |Closed Date             |Agency |Agency Name                                        |Complaint Type |Descriptor |Location Type        |Incident Zip |Incident Address     |Street Name      |Cross Street 1 |Cross Street 2 |Intersection Street 1 |Intersection Street 2 |Address Type |City    |Landmark |Facility Type |Status |Due Date |Resolution Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |Resolution Action Updated Date |Community Board |BBL        |Borough | X Coordinate (State Plane)| Y Coordinate (State Plane)|Open Data Channel Type |Park Facility Name |Park Borough |Vehicle Type |Taxi Company Borough |Taxi Pick Up Location |Bridge Highway Name |Bridge Highway Direction |Road Ramp |Bridge Highway Segment | Latitude| Longitude|Location                                |created_date |closed_date |Year |Month         | resolution_days|Borough_Mapped |\n|:----------|:-----------------------|:-----------------------|:------|:--------------------------------------------------|:--------------|:----------|:--------------------|:------------|:--------------------|:----------------|:--------------|:--------------|:---------------------|:---------------------|:------------|:-------|:--------|:-------------|:------|:--------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|:------------------------------|:---------------|:----------|:-------|--------------------------:|--------------------------:|:----------------------|:------------------|:------------|:------------|:--------------------|:---------------------|:-------------------|:------------------------|:---------|:----------------------|--------:|---------:|:---------------------------------------|:------------|:-----------|:----|:-------------|---------------:|:--------------|\n|63573695   |2024-12-31T23:06:14.000 |2025-01-19T11:58:36.000 |HPD    |Department of Housing Preservation and Development |Mold           |MOLD       |RESIDENTIAL BUILDING |10451        |283 EAST  149 STREET |EAST  149 STREET |NA             |NA             |NA                    |NA                    |ADDRESS      |BRONX   |NA       |NA            |Closed |NA       |HPD conducted an inspection of this complaint. The conditions observed by the inspector did not violate the housing laws enforced by HPD. The complaint has been closed.                                                                                                                                                                                                                                                                                                                                             |2025-01-19T00:00:00.000        |01 BRONX        |2023310072 |BRONX   |                    1005910|                     236991|PHONE                  |Unspecified        |BRONX        |NA           |NA                   |NA                    |NA                  |NA                       |NA        |NA                     | 40.81713| -73.92175|(40.81713468822815, -73.9217467475281)  |2024-12-31   |2025-01-19  |2024 |12 - December |              19|BRONX          |\n|63583460   |2024-12-31T21:19:39.000 |2025-01-03T16:24:36.000 |HPD    |Department of Housing Preservation and Development |Mold           |MOLD       |RESIDENTIAL BUILDING |10468        |2719 MORRIS AVENUE   |MORRIS AVENUE    |NA             |NA             |NA                    |NA                    |ADDRESS      |BRONX   |NA       |NA            |Closed |NA       |HPD inspected this condition so the complaint has been closed. Violations were issued. The law provides the property owner time to correct the condition(s).  Violation descriptions and the dates for the property owner to correct any violations are available at HPDONLINE.  If the owner has not corrected the condition by the date provided, you may wish to bring a case in housing court seeking the correction of these conditions.To find out more about how to start a housing court case, visit HPD's w |2025-01-03T00:00:00.000        |07 BRONX        |2033170043 |BRONX   |                    1013153|                     255563|PHONE                  |Unspecified        |BRONX        |NA           |NA                   |NA                    |NA                  |NA                       |NA        |NA                     | 40.86809| -73.89550|(40.86808863174485, -73.89549921281306) |2024-12-31   |2025-01-03  |2024 |12 - December |               3|BRONX          |\n|63583408   |2024-12-31T20:55:28.000 |2025-01-10T16:55:45.000 |HPD    |Department of Housing Preservation and Development |Mold           |MOLD       |RESIDENTIAL BUILDING |11435        |85-15 139 STREET     |139 STREET       |NA             |NA             |NA                    |NA                    |ADDRESS      |JAMAICA |NA       |NA            |Closed |NA       |HPD conducted an inspection of this complaint. The conditions observed by the inspector did not violate the housing laws enforced by HPD. The complaint has been closed.                                                                                                                                                                                                                                                                                                                                             |2025-01-10T00:00:00.000        |08 QUEENS       |4097100002 |QUEENS  |                    1034989|                     197495|PHONE                  |Unspecified        |QUEENS       |NA           |NA                   |NA                    |NA                  |NA                       |NA        |NA                     | 40.70861| -73.81699|(40.7086094282564, -73.8169884642595)   |2024-12-31   |2025-01-10  |2024 |12 - December |              10|QUEENS         |\n\n\n:::\n:::\n\n\n\n::: {#tbl-dv_data_clean .cell}\n\n```{.r .cell-code}\nkable(head(dv_data_clean, 5),\n      caption = \"Preview of cleaned NYPD complaint records used to identify domestic violence reports (first 5 rows) after renaming fields and extracting date components.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Preview of cleaned NYPD complaint records used to identify domestic violence reports (first 5 rows) after renaming fields and extracting date components.\n\n|complaint_number |inc_occur_date          |inc_occur_time |inc_end_date            |inc_end_time | precinct_occur|report_date             | key_code|offense_type                 | class_code|class_code_desc |attempt_completion |offense_level |borough |LOC_OF_OCCUR_DESC |PREM_TYP_DESC          |JURIS_DESC       | JURISDICTION_CODE|PARKS_NM |HADEVELOPT |HOUSING_PSA | X_COORD_CD| Y_COORD_CD|suspect_age |suspect_race |suspect_sex |TRANSIT_DISTRICT | Latitude| Longitude|Lat_Lon                 |PATROL_BORO              |STATION_NAME |victim_age |victim_race    |victim_sex |inc_date_converted |Year |Month         |complaint |\n|:----------------|:-----------------------|:--------------|:-----------------------|:------------|--------------:|:-----------------------|--------:|:----------------------------|----------:|:---------------|:------------------|:-------------|:-------|:-----------------|:----------------------|:----------------|-----------------:|:--------|:----------|:-----------|----------:|----------:|:-----------|:------------|:-----------|:----------------|--------:|---------:|:-----------------------|:------------------------|:------------|:----------|:--------------|:----------|:------------------|:----|:-------------|:---------|\n|298690828        |2024-12-31T00:00:00.000 |13:00:00       |2024-12-31T00:00:00.000 |13:10:00     |            113|2024-12-31T00:00:00.000 |      344|ASSAULT 3 & RELATED OFFENSES |        101|ASSAULT 3       |COMPLETED          |MISDEMEANOR   |QUEENS  |INSIDE            |RESIDENCE-HOUSE        |N.Y. POLICE DEPT |                 0|(null)   |(null)     |NA          |    1046104|     187464|<18         |BLACK        |F           |NA               | 40.68101| -73.77699|(40.681014, -73.776991) |PATROL BORO QUEENS SOUTH |(null)       |<18        |BLACK          |M          |2024-12-31         |2024 |12 - December |DV        |\n|298698016        |2024-12-31T00:00:00.000 |08:00:00       |2024-12-31T00:00:00.000 |09:00:00     |            116|2024-12-31T00:00:00.000 |      344|ASSAULT 3 & RELATED OFFENSES |        101|ASSAULT 3       |COMPLETED          |MISDEMEANOR   |QUEENS  |INSIDE            |RESIDENCE-HOUSE        |N.Y. POLICE DEPT |                 0|(null)   |(null)     |NA          |    1048028|     178970|25-44       |BLACK        |M           |NA               | 40.65769| -73.77013|(40.657687, -73.770132) |PATROL BORO QUEENS SOUTH |(null)       |18-24      |WHITE HISPANIC |F          |2024-12-31         |2024 |12 - December |DV        |\n|298704508        |2024-12-31T00:00:00.000 |16:50:00       |2024-12-31T00:00:00.000 |16:56:00     |            107|2024-12-31T00:00:00.000 |      344|ASSAULT 3 & RELATED OFFENSES |        101|ASSAULT 3       |COMPLETED          |MISDEMEANOR   |QUEENS  |INSIDE            |RESIDENCE - APT. HOUSE |N.Y. POLICE DEPT |                 0|(null)   |(null)     |NA          |    1050645|     203097|UNKNOWN     |BLACK        |F           |NA               | 40.72389| -73.76046|(40.723891, -73.760464) |PATROL BORO QUEENS SOUTH |(null)       |65+        |WHITE          |M          |2024-12-31         |2024 |12 - December |DV        |\n|298678676        |2024-12-31T00:00:00.000 |07:00:00       |2024-12-31T00:00:00.000 |07:30:00     |            113|2024-12-31T00:00:00.000 |      344|ASSAULT 3 & RELATED OFFENSES |        101|ASSAULT 3       |COMPLETED          |MISDEMEANOR   |QUEENS  |INSIDE            |RESIDENCE-HOUSE        |N.Y. POLICE DEPT |                 0|(null)   |(null)     |NA          |    1051478|     189936|25-44       |BLACK        |M           |NA               | 40.68776| -73.75759|(40.687762, -73.757589) |PATROL BORO QUEENS SOUTH |(null)       |45-64      |BLACK          |M          |2024-12-31         |2024 |12 - December |DV        |\n|298672417        |2024-12-31T00:00:00.000 |02:50:00       |2024-12-31T00:00:00.000 |02:55:00     |            101|2024-12-31T00:00:00.000 |      344|ASSAULT 3 & RELATED OFFENSES |        101|ASSAULT 3       |COMPLETED          |MISDEMEANOR   |QUEENS  |INSIDE            |RESIDENCE-HOUSE        |N.Y. POLICE DEPT |                 0|(null)   |(null)     |NA          |    1054075|     157436|45-64       |BLACK        |M           |NA               | 40.59854| -73.74856|(40.598536, -73.74856)  |PATROL BORO QUEENS SOUTH |(null)       |45-64      |BLACK          |F          |2024-12-31         |2024 |12 - December |DV        |\n\n\n:::\n:::\n\n\n\nThis chunk deals with some heavy cleaning of large datasets; I am mostly standardizing column names, values, filling in NA values for Borough (using the City column), and getting rid of otherwise NA values. I also separated the dates so that Year, Month, and Day could be individually utilized in the project.\n\n### Aggregating Mold Data & DV Data\n\n\n::: {#tbl-agg .cell}\n\n```{.r .cell-code}\naggregated_dv_data <- dv_data_clean %>%\n  group_by(Year, Month, borough) %>%\n  summarise(\n    `complaint` = n(),\n    .groups = \"drop\"\n  )\naggregated_dv_data <- aggregated_dv_data %>%\n  filter(borough != \"(null)\")\n\naggregated_dv_data <- aggregated_dv_data %>%\n  mutate(Year = as.character(Year))\n\naggregated_dv_data<- aggregated_dv_data %>% rename(\n  \"Borough\" = \"borough\")\n\naggregated_dv_data<- aggregated_dv_data %>% rename(\n  \"DV Reports\" = \"complaint\"\n)\n\naggregated_mold_data <- mold_data_clean %>%\n  group_by(Year, Month, Borough) %>%\n  summarise(\n  `Complaint Type` = n(),\n  .groups = \"drop\"\n)\n\naggregated_mold_data<- aggregated_mold_data %>% rename(\n  \"Mold Complaints\" = \"Complaint Type\"\n)\n\naggregated_dv_mold_data <- left_join(\n  aggregated_dv_data,\n  aggregated_mold_data,\n  by = c(\"Borough\", \"Year\", \"Month\")\n)\n\naggregated_dv_mold_data <- aggregated_dv_mold_data %>%\n  mutate(\n    year_month = paste(Year, Month)\n  )\n\naggregated_dv_mold_data <- aggregated_dv_mold_data %>%\n  group_by(Borough) %>%\n  mutate(time_index = row_number()) %>%\n  ungroup()\n\nkable(head(aggregated_dv_mold_data, 15),\n      caption = \"Monthly borough-level dataset combining domestic violence report counts and residential mold complaint counts (first 15 rows).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Monthly borough-level dataset combining domestic violence report counts and residential mold complaint counts (first 15 rows).\n\n|Year |Month         |Borough       | DV Reports| Mold Complaints|year_month         | time_index|\n|:----|:-------------|:-------------|----------:|---------------:|:------------------|----------:|\n|2010 |01 - January  |BRONX         |        910|             954|2010 01 - January  |          1|\n|2010 |01 - January  |BROOKLYN      |       1306|             779|2010 01 - January  |          1|\n|2010 |01 - January  |MANHATTAN     |        541|             410|2010 01 - January  |          1|\n|2010 |01 - January  |QUEENS        |        791|             315|2010 01 - January  |          1|\n|2010 |01 - January  |STATEN ISLAND |        154|              58|2010 01 - January  |          1|\n|2010 |02 - February |BRONX         |        818|             738|2010 02 - February |          2|\n|2010 |02 - February |BROOKLYN      |        938|             651|2010 02 - February |          2|\n|2010 |02 - February |MANHATTAN     |        424|             338|2010 02 - February |          2|\n|2010 |02 - February |QUEENS        |        603|             273|2010 02 - February |          2|\n|2010 |02 - February |STATEN ISLAND |        151|              29|2010 02 - February |          2|\n|2010 |03 - March    |BRONX         |        969|             941|2010 03 - March    |          3|\n|2010 |03 - March    |BROOKLYN      |       1149|             870|2010 03 - March    |          3|\n|2010 |03 - March    |MANHATTAN     |        500|             415|2010 03 - March    |          3|\n|2010 |03 - March    |QUEENS        |        758|             395|2010 03 - March    |          3|\n|2010 |03 - March    |STATEN ISLAND |        147|              55|2010 03 - March    |          3|\n\n\n:::\n:::\n\n\nIn this chunk, I aggregated the domestic violence reports and mold complaints datasets into one, grouped by month and borough, in order to easily analyze trends.\n\n## Exploring the Data\n\n### Domestic Violence Data\n\n#### Summary Stats\n\n\n::: {#tbl-dv-data .cell}\n\n```{.r .cell-code}\ndv_summary <- aggregated_dv_data %>%\n  summarise(\n    total_reports = sum(`DV Reports`),\n    start_year = min(as.numeric(Year)),\n    end_year = max(as.numeric(Year)),\n    boroughs = n_distinct(Borough),\n    avg_monthly = mean(`DV Reports`)\n  )\n\nkable(dv_summary,\n      caption = \"Summary of domestic violence reports in NYC (2010–2024), aggregated from NYPD complaint data.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of domestic violence reports in NYC (2010–2024), aggregated from NYPD complaint data.\n\n| total_reports| start_year| end_year| boroughs| avg_monthly|\n|-------------:|----------:|--------:|--------:|-----------:|\n|        669136|       2010|     2024|        5|    743.4844|\n\n\n:::\n:::\n\n\nFrom the beginning of the year in 2010 to the end of the year in 2024, there were a total of 669,136 domestic violence incidents reported across all five boroughs in New York City. Without grouping by year or borough, there are roughly 743 domestic violence incident reports filed each month.\n\n#### Borough/Year Distribution\n\n\n::: {#tbl-boro .cell}\n\n```{.r .cell-code}\ndv_by_year_borough <- aggregated_dv_data %>%\n  group_by(Year, Borough) %>%\n  summarise(total_reports = sum(`DV Reports`)) %>%\n  pivot_wider(names_from = Year,\n    values_from = total_reports)\n\nkable(dv_by_year_borough,\n      caption = \"Total domestic violence reports by borough and year (2010–2024).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Total domestic violence reports by borough and year (2010–2024).\n\n|Borough       |  2010|  2011|  2012|  2013|  2014|  2015|  2016|  2017|  2018|  2019|  2020|  2021|  2022|  2023|  2024|\n|:-------------|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|\n|BRONX         | 11274| 11441| 12207| 12630| 12924| 12594| 12916| 12569| 13662| 12943| 12013| 12499| 14193| 14149| 14905|\n|BROOKLYN      | 14094| 14344| 15232| 15032| 15022| 14101| 13771| 13052| 13039| 12250| 11256| 12362| 13286| 13180| 13652|\n|MANHATTAN     |  6081|  6128|  6471|  6409|  6627|  6555|  6791|  6586|  6550|  6864|  6117|  7160|  7194|  6880|  7215|\n|QUEENS        |  8726|  9182|  9128|  9425|  9467|  8906|  8697|  8733|  9047|  9324|  8778|  9368| 10205| 10484| 12071|\n|STATEN ISLAND |  2015|  2056|  2414|  2242|  2364|  2178|  2112|  2036|  2048|  1868|  1687|  1871|  2099|  2126|  2259|\n\n\n:::\n:::\n\n\nFrom 2010 to 2024, Brooklyn and Bronx have consistently had the highest amount of domestic violence reports in NYC. Brooklyn was the borough with the most amount of reports since 2010, but sometime in 2018, Bronx took the title for highest reported incidents and has been the borough with the highest number of reports since then. Staten Island has had the lowest reported incidents each year.\n\nFor the most part, domestic violence incident reports have risen across the boroughs consistently from 2010-2024. However, Brooklyn is the only borough in which the number of reported incidents are lower in 2024 than they were in 2010. (This could be something interesting to look into!)\n\n#### Heat Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\ndv_plot_data <- aggregated_dv_data %>%\n  group_by(Year, Borough) %>%\n  summarise(total_reports = sum(`DV Reports`))\n\nggplot(dv_plot_data, aes(x = Year, y = Borough, fill = total_reports)) +\n  geom_tile(color = \"white\") +\n  scale_fill_gradient(low = \"lightblue\", high = \"darkred\") +\n  labs(\n    title = \"DV Reports by Borough and Year\",\n    x = \"Year\",\n    y = \"Borough\",\n    fill = \"DV Reports\"\n  ) +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45))\n```\n\n::: {.cell-output-display}\n![Domestic violence reports by borough and year (2010–2024).](06-ToxicHomes-Shannon_files/figure-html/fig-dv-chart-1.png){#fig-dv-chart fig-alt='Heat map showing yearly domestic violence report counts for each NYC borough from 2010 to 2024. Color intensity increases as report totals increase.' width=672}\n:::\n:::\n\n\nAbove is a heat map of domestic violence incident reports from 2010-2024. This reflects what was observed in the previous table; The Bronx and Brooklyn typically tend to have a higher volume of reports, and Staten Island has stayed largely below the average.\n\n### Mold Exposure Data\n\n### Summary Stats\n\n\n::: {#tbl-mold-data .cell}\n\n```{.r .cell-code}\nmold_summary <- aggregated_mold_data %>%\n  summarise(\n    total_complaints = sum(`Mold Complaints`),\n    start_year = min(as.numeric(Year)),\n    end_year = max(as.numeric(Year)),\n    boroughs = n_distinct(Borough),\n    avg_monthly = mean(`Mold Complaints`)\n  )\n\nkable(mold_summary,\n      caption = \"Summary of residential mold complaints in NYC (2010–2024), aggregated from 311 service requests.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of residential mold complaints in NYC (2010–2024), aggregated from 311 service requests.\n\n| total_complaints| start_year| end_year| boroughs| avg_monthly|\n|----------------:|----------:|--------:|--------:|-----------:|\n|           361603|       2010|     2024|        5|    445.3239|\n\n\n:::\n:::\n\n\nFrom 2010-2025, there have been a total of 412,698 mold complaints in residential buildings reported across all five boroughs in New York City. Without grouping by year or borough, there are roughly 431 residential mold complaints made to 311 every month.\n\n### Borough/Year Distributions\n\n\n::: {#tbl-boro-mold .cell}\n\n```{.r .cell-code}\nmold_by_year_borough <- aggregated_mold_data %>%\n  group_by(Year, Borough) %>%\n  summarise(total_complaints = sum(`Mold Complaints`)) %>%\n  pivot_wider(names_from = Year,\n    values_from = total_complaints)\n\nkable(mold_by_year_borough,\n      caption = \"Total residential mold complaints by borough and year (2010–2024).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Total residential mold complaints by borough and year (2010–2024).\n\n|Borough       | 2010|  2011| 2012| 2013| 2014| 2015| 2016| 2017| 2018| 2019| 2020| 2021| 2022|  2023|  2024|\n|:-------------|----:|-----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|-----:|-----:|\n|BRONX         | 7973|  8726| 7384| 7778| 8295| 8434| 7946| 7510| 9510| 6460| 5953| 9378| 9513| 11438| 12847|\n|BROOKLYN      | 8244| 10404| 8373| 9299| 9280| 9074| 7700| 7908| 9747| 6360| 5397| 8199| 8265| 10389| 11092|\n|MANHATTAN     | 3977|  4403| 3683| 3840| 4787| 5062| 4395| 4031| 4942| 3119| 2985| 5027| 5347|  6660|  6757|\n|QUEENS        | 3258|  3907| 2414|    2|   NA|    2|    3|    1|    3|   12|    1|  872| 3347|  4229|  4736|\n|STATEN ISLAND |  615|   852|  730|  757|  747|  688|  720|  691|  864|  529|  504|  777|  721|   960|   770|\n\n\n:::\n:::\n\n\nFrom 2010 to 2024, Brooklyn and Bronx seem to have the highest complaints of mold in residential buildings, and they compete for first place. Staten Island was found to have the lowest number of residential mold complaints to 311 each year.\n\nAcross all 5 boroughs, there are more mold complaints in 2024 than there were in 2010, with the overall trend being an increase in 311 complaints for residential mold.\n\n### Heat Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmold_plot_data <- aggregated_mold_data %>%\n  group_by(Year, Borough) %>%\n  summarise(total_complaints = sum(`Mold Complaints`))\n\nggplot(mold_plot_data, aes(x = Year, y = Borough, fill = total_complaints)) +\n  geom_tile(color = \"white\") +\n  scale_fill_gradient(low = \"wheat\", high = \"darkgreen\") +\n  labs(\n    title = \"Mold Complaints by Borough and Year\",\n    x = \"Year\",\n    y = \"Borough\",\n    fill = \"Mold Complaints\"\n  ) +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45))\n```\n\n::: {.cell-output-display}\n![Residential mold complaints by borough and year (2010–2024).](06-ToxicHomes-Shannon_files/figure-html/fig-mold-chart-1.png){#fig-mold-chart fig-alt='Heat map showing yearly residential mold complaint totals for each NYC borough from 2010 to 2024. Darker shading indicates higher complaint counts.' width=672}\n:::\n:::\n\n\nAbove is a heat map of residential mold complaints to 311 from 2010-2025. Similar in density to the domestic violence report heat map; The Bronx and Brooklyn seem to have a higher volume of complaints, and Staten Island has stayed largely below the average.\n\n### Preliminary Correlation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(aggregated_dv_mold_data$`DV Reports`, \n         aggregated_dv_mold_data$`Mold Complaints`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  x and y\nt = 42.034, df = 810, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.8051174 0.8485104\nsample estimates:\n      cor \n0.8280499 \n```\n\n\n:::\n:::\n\n\n-   Strength: 0.82 (very strong)\n\n-   Direction: positive\n\n-   Significance: statistically significant (p\\<0.05)\n\nI ran a correlation between domestic violence reports and residential mold complaints to see if there was a substantial relationship between them, and there is! The relationship between the two is positive and very strong, suggesting that a higher amount of DV reports is associated with a higher amount of mold complaints, and a lower number of DV reports is associated with a lower amount of mold complaints. This tells us that both variables move together.\n\n##### Let's visualize this:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(aggregated_dv_mold_data, aes(x = `Mold Complaints`, y = `DV Reports`, color = Borough)) +\n  geom_point(alpha = 0.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"gray18\") +\n  labs(title = \"DV Reports vs Mold Complaints by Borough\",\n       x = \"Mold Complaints\",\n       y = \"DV Reports\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Association between monthly residential mold complaints and domestic violence reports by borough (2010–2024).](06-ToxicHomes-Shannon_files/figure-html/fig-corr-plot-1.png){#fig-corr-plot fig-alt='Scatter plot of monthly borough-level observations with mold complaints on the x-axis and domestic violence reports on the y-axis. Points are colored by borough and a single linear trend line summarizes the overall relationship.' width=672}\n:::\n:::\n\n\nHowever, this only tells us that domestic violence reports and mold complaints co-occur, and it does not tell us anything about causality.\n\nLet's dive into how domestic violence reports and mold complaints develop over time!\n\n## Temporal Trends\n\n#### Yearly Counts\n\n\n::: {#tbl-yearly-counts .cell}\n\n```{.r .cell-code}\nyearly_counts_wide <- aggregated_dv_mold_data %>%\n  group_by(Year) %>%\n  summarise(\n    `DV Reports` = sum(`DV Reports`, na.rm = TRUE),\n    `Mold Complaints` = sum(`Mold Complaints`, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  pivot_longer(\n    cols = c(`DV Reports`, `Mold Complaints`),\n    names_to = \"Type\",\n    values_to = \"Count\"\n  ) %>%\n  pivot_wider(\n    names_from = Year,\n    values_from = Count\n  )\n\nkable(yearly_counts_wide,\n      caption = \"Citywide totals by year for domestic violence reports and residential mold complaints (2010–2024).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Citywide totals by year for domestic violence reports and residential mold complaints (2010–2024).\n\n|Type            |  2010|  2011|  2012|  2013|  2014|  2015|  2016|  2017|  2018|  2019|  2020|  2021|  2022|  2023|  2024|\n|:---------------|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|\n|DV Reports      | 42190| 43151| 45452| 45738| 46404| 44334| 44287| 42976| 44346| 43249| 39851| 43260| 46977| 46819| 50102|\n|Mold Complaints | 24067| 28292| 22584| 21676| 23109| 23260| 20764| 20141| 25066| 16480| 14840| 24253| 27193| 33676| 36202|\n\n\n:::\n:::\n\n\nLooking at this table, we can see that DV reports and mold complaints have staggered over the years, but overall they seem to have an increasing trend. Both variables have higher reports in 2024 than they did in 2010.\n\n#### Monthly Counts\n\n\n::: {#tbl-monthly-counts .cell}\n\n```{.r .cell-code}\nmonthly_counts <- aggregated_dv_mold_data %>%\n  group_by(Year, Month) %>%\n  summarise(\n    total_dv = sum(`DV Reports`, na.rm = TRUE),\n    total_mold = sum(`Mold Complaints`, na.rm = TRUE)\n  )\n\nkable(head(monthly_counts, 12),\n      caption = \"First 12 rows of citywide monthly totals for domestic violence reports and residential mold complaints (2010–2024).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: First 12 rows of citywide monthly totals for domestic violence reports and residential mold complaints (2010–2024).\n\n|Year |Month          | total_dv| total_mold|\n|:----|:--------------|--------:|----------:|\n|2010 |01 - January   |     3702|       2516|\n|2010 |02 - February  |     2934|       2029|\n|2010 |03 - March     |     3523|       2676|\n|2010 |04 - April     |     3343|       2251|\n|2010 |05 - May       |     3583|       1787|\n|2010 |06 - June      |     3867|       1856|\n|2010 |07 - July      |     3872|       1765|\n|2010 |08 - August    |     3617|       1958|\n|2010 |09 - September |     3618|       1766|\n|2010 |10 - October   |     3542|       1969|\n|2010 |11 - November  |     3365|       1661|\n|2010 |12 - December  |     3224|       1833|\n\n\n:::\n:::\n\n\nAbove is a table that separates the total domestic violence reports and mold complaints by each month per year. If we plot this, we can see how they both trend over time compared to one another:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_data <- aggregated_dv_mold_data %>%\n  pivot_longer(\n    cols = c(`DV Reports`, `Mold Complaints`),\n    names_to = \"Type\",\n    values_to = \"Count\"\n  )\n\nggplot(plot_data, aes(x = time_index, y = Count, color = Type)) +\n  geom_line(linewidth = 0.5) +\n  facet_wrap(~Borough) +\n  scale_color_manual(values = c(\"DV Reports\" = \"darkred\", \"Mold Complaints\" = \"darkgreen\")) +\n  labs(\n    title = \"Monthly DV and Mold Reports by Borough\",\n    x = \"Time\",\n    y = \"Number of Reports\",\n    color = \"Report Type\"\n  ) +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45)\n  )\n```\n\n::: {.cell-output-display}\n![Monthly trends in domestic violence reports and mold complaints by borough (2010–2024).](06-ToxicHomes-Shannon_files/figure-html/fig-temporal-plots-1.png){#fig-temporal-plots fig-alt='Faceted line chart with one panel per borough. Two time series per panel show monthly counts of domestic violence reports and residential mold complaints from 2010 through 2024, illustrating seasonal peaks and long-run trends.' width=672}\n:::\n:::\n\n\nHere, we have line plots of domestic violence reports and residential mold complaints per month from January of 2010 to December of 2024 (faceted by borough). We can see similar peaks across the boroughs (especially The Bronx and Brooklyn).\n\nSo, how **exactly** does mold exposure relate to domestic violence reports over time?\n\nWe've established that a relationship exists between the two variables themselves, but we need to look closer at this data. How does domestic violence in a given borough during a given month correlate with mold complaints in the same borough during the same month, and how does **those** variables move together?\n\nMonth-by-Month DV vs. Mold Counts\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(monthly_counts$total_dv, monthly_counts$total_mold)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  x and y\nt = 5.5339, df = 178, p-value = 1.106e-07\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.2509287 0.5013019\nsample estimates:\n      cor \n0.3831305 \n```\n\n\n:::\n:::\n\n\n-   Strength: 0.36\n\n-   Direction: positive\n\n-   Significance: statistically significant (p\\<0.05)\n\nThis is a much more realistic look at how mold complaints and DV reports move together across time! We got rid of borough size differences and were able to focus on the complaints and reports that were really happening in the same area during the same time. We can see that month-by-month DV reports and mold complaints have a moderate, positive correlation with one another and this result is statistically significant. This suggests that mold complaints and DV reports tend to coincide with each other each month.\n\n### Exploring Mold Resolution\n\nCounts of mold complaints provide insight into the amount of housing issues that exist, but they do not tell us how long the residents are dealing with the exposure to mold. When investigating predictors of household stress, the length of time a complaint remains unresolved may be important.\n\nSo, let's take a look at how resolution time may play a role in the relationship between domestic violence reports and mold complaints:\n\n### Quick Look at Resolution Time\n\n\n::: {#tbl-res-time .cell}\n\n```{.r .cell-code}\nres_time<- mold_data_clean %>%\n  group_by(Borough) %>%\n  summarise(\n    avg_resolution_days = mean(resolution_days, na.rm = TRUE),\n    median_days = median(resolution_days, na.rm = TRUE),\n    min_days = min(resolution_days, na.rm = TRUE),\n    max_days = max(resolution_days, na.rm = TRUE),\n    n_complaints = n()\n  ) %>%\n  arrange(desc(avg_resolution_days))\n\nkable(res_time,\n      caption = \"Residential mold complaint resolution time by borough (days between created and closed dates).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Residential mold complaint resolution time by borough (days between created and closed dates).\n\n|Borough       | avg_resolution_days| median_days| min_days| max_days| n_complaints|\n|:-------------|-------------------:|-----------:|--------:|--------:|------------:|\n|MANHATTAN     |            20.60248|          11|        0|     3090|        69015|\n|STATEN ISLAND |            17.67769|          11|        0|      805|        10925|\n|QUEENS        |            15.58721|           8|        0|     4184|        22787|\n|BRONX         |            15.02155|          10|        0|      975|       129145|\n|BROOKLYN      |            14.03738|           9|        0|     3980|       129731|\n\n\n:::\n:::\n\n\nRight away, we see a huge variation in the amount of days it has taken for a residential mold complaint to be resolved. Some reports are addressed as early as the same day, while others can take years to be fully resolved. The average amount of days it takes for a complaint to be resolved varies per borough, but it is roughly between 14 to 21 days, or 2 to 3 weeks.\n\n### Average Resolution Delay per Month\n\n\n::: {#tbl-avg-res-delay .cell}\n\n```{.r .cell-code}\nmold_monthly_resolution <- mold_data_clean %>%\n  group_by(Year, Month) %>%\n  summarise(\n    avg_resolution_days = mean(resolution_days, na.rm = TRUE),\n    n_complaints = n()\n  ) %>%\n  arrange(Year, Month)\n\nkable(head(mold_monthly_resolution, 12),\n      caption = \"First 12 rows of monthly average mold-complaint resolution time (in days), with complaint volume.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: First 12 rows of monthly average mold-complaint resolution time (in days), with complaint volume.\n\n|Year |Month          | avg_resolution_days| n_complaints|\n|:----|:--------------|-------------------:|------------:|\n|2010 |01 - January   |            20.31474|         2516|\n|2010 |02 - February  |            16.09571|         2029|\n|2010 |03 - March     |            15.59963|         2676|\n|2010 |04 - April     |            14.46246|         2251|\n|2010 |05 - May       |            14.81757|         1787|\n|2010 |06 - June      |            14.81358|         1856|\n|2010 |07 - July      |            14.59217|         1765|\n|2010 |08 - August    |            14.01535|         1958|\n|2010 |09 - September |            13.32578|         1766|\n|2010 |10 - October   |            18.39756|         1969|\n|2010 |11 - November  |            20.97167|         1661|\n|2010 |12 - December  |            26.94590|         1833|\n\n\n:::\n:::\n\n\nAbove, we see the monthly average amount of days it took to resolve a mold complaint in 2010. This closely follows our averages from the previous table, with December as a bit of an outlier.\n\n### Lagged Data\n\n\n::: {#tbl-lag .cell}\n\n```{.r .cell-code}\ndv_mold_lagged <- aggregated_dv_mold_data %>%\n  arrange(Borough, time_index) %>%\n  group_by(Borough) %>%\n  mutate(DV_next_month = lead(`DV Reports`, n = 1)) %>%\n  ungroup()\n\nkable(head(dv_mold_lagged, 12),\n      caption = \"Lagged dataset preview: current-month mold complaints matched to next-month domestic violence reports (first 12 rows).\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Lagged dataset preview: current-month mold complaints matched to next-month domestic violence reports (first 12 rows).\n\n|Year |Month          |Borough | DV Reports| Mold Complaints|year_month          | time_index| DV_next_month|\n|:----|:--------------|:-------|----------:|---------------:|:-------------------|----------:|-------------:|\n|2010 |01 - January   |BRONX   |        910|             954|2010 01 - January   |          1|           818|\n|2010 |02 - February  |BRONX   |        818|             738|2010 02 - February  |          2|           969|\n|2010 |03 - March     |BRONX   |        969|             941|2010 03 - March     |          3|           875|\n|2010 |04 - April     |BRONX   |        875|             798|2010 04 - April     |          4|           940|\n|2010 |05 - May       |BRONX   |        940|             576|2010 05 - May       |          5|          1015|\n|2010 |06 - June      |BRONX   |       1015|             582|2010 06 - June      |          6|          1043|\n|2010 |07 - July      |BRONX   |       1043|             553|2010 07 - July      |          7|           970|\n|2010 |08 - August    |BRONX   |        970|             528|2010 08 - August    |          8|           983|\n|2010 |09 - September |BRONX   |        983|             534|2010 09 - September |          9|           914|\n|2010 |10 - October   |BRONX   |        914|             562|2010 10 - October   |         10|           959|\n|2010 |11 - November  |BRONX   |        959|             513|2010 11 - November  |         11|           878|\n|2010 |12 - December  |BRONX   |        878|             694|2010 12 - December  |         12|          1052|\n\n\n:::\n:::\n\n\nBecause psychological effects related to mold exposure may not develop immediately, I wanted to explore whether there are delayed temporal patterns between mold complaints and domestic violence reports. Specifically, if mold complaints increase in one month, could this be associated with higher levels of domestic violence in the following month?\n\nTo examine this, I created a lagged dataset that matches residential mold complaints from one month with domestic violence incidents reported in the following month.\n\n##### Let's visualize what this looks like:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dv_mold_lagged, aes(x = `Mold Complaints`, y = DV_next_month)) +\n  geom_point(alpha = 0.5, color = \"darkgreen\") +\n  geom_smooth(method = \"lm\", color = \"darkred\") +\n  labs(\n    title = \"Next Month DV Reports vs Current Month Mold Complaints\",\n    x = \"Mold Complaints (Current Month)\",\n    y = \"DV Reports (Next Month)\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![Lagged association: next-month domestic violence reports versus current-month mold complaints (borough-month observations).](06-ToxicHomes-Shannon_files/figure-html/fig-lag-plot-1.png){#fig-lag-plot fig-alt='Scatter plot of borough-month observations with current-month mold complaints on the x-axis and next-month domestic violence reports on the y-axis. A fitted linear trend line indicates whether higher mold complaint counts tend to precede higher DV reports.' width=672}\n:::\n:::\n\n\nThese two variables still look very closely related! But, does time passing really have anything to do with it?\n\nLet's conduct some statistical tests to dig deeper!\n\n## Statistical Analysis\n\n#### Lagged Data Correlation Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(dv_mold_lagged$DV_next_month, dv_mold_lagged$`Mold Complaints`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  x and y\nt = 40.376, df = 805, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.7940136 0.8397855\nsample estimates:\n      cor \n0.8181918 \n```\n\n\n:::\n:::\n\n\nI conducted a Pearson's correlation test to examine the relationship between mold complaints in one month and DV reports the following month.\n\n-   Strength: 0.81 (very strong)\n\n-   Direction: positive\n\n-   Significance: statistically significant (p\\<0.05)\n\nThe results show a very strong positive correlation, suggesting that months with higher mold complaint counts are associated with higher domestic violence reports in the following month. However, this result is similar to the basic correlation between mold complaints and DV reports (conducted earlier on) and does not account for other factors that might influence the relationship, such as borough.\n\nTo better understand how additional variables (such as borough and average resolution time) affect this association, I conducted regression analyses.\n\n## Regression Models\n\n#### DV \\~ Mold\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregated_dv_mold_data <- aggregated_dv_mold_data %>%\n  mutate(Borough = factor(Borough)) %>%\n  arrange(Year, Month)\n\nlm_dv_mold <- lm(`DV Reports` ~ `Mold Complaints`,\n  data = aggregated_dv_mold_data)\n\nsummary(lm_dv_mold)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `DV Reports` ~ `Mold Complaints`, data = aggregated_dv_mold_data)\n\nResiduals:\n   Min     1Q Median     3Q    Max \n-920.1 -164.7  -41.6  150.6  626.1 \n\nCoefficients:\n                   Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       285.96840   13.20783   21.65   <2e-16 ***\n`Mold Complaints`   1.02460    0.02438   42.03   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 214.4 on 810 degrees of freedom\n  (88 observations deleted due to missingness)\nMultiple R-squared:  0.6857,\tAdjusted R-squared:  0.6853 \nF-statistic:  1767 on 1 and 810 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(lm_dv_mold)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 11025.83\n```\n\n\n:::\n:::\n\n\nThis linear regression model tests the association between monthly residential mold complaints and domestic violence reports across all 5 boroughs and all time periods.\n\n-   Strength: strong (R\\^2 = 0.67)\n\n-   Direction: positive\n\n-   Significance: statistically significant (p\\<0.05)\n\n-   AIC: 12160.34\n\nResults suggest a strong and statistically significant positive association between mold complaints and DV reports. On average, months with higher numbers of mold complaints are associated with higher numbers of reported domestic violence incidents. However, this model does not account for differences across boroughs or temporal patterns.\n\n#### DV \\~ Mold + Borough\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm_borough <- lm(\n  `DV Reports` ~ `Mold Complaints` + Borough,\n  data = aggregated_dv_mold_data\n)\n\nsummary(lm_borough)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `DV Reports` ~ `Mold Complaints` + Borough, data = aggregated_dv_mold_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-257.74  -41.60   -3.30   37.16  396.94 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           933.14621   15.35068  60.789  < 2e-16 ***\n`Mold Complaints`       0.19321    0.01945   9.935  < 2e-16 ***\nBoroughBROOKLYN        59.11542    9.04790   6.534 1.14e-10 ***\nBoroughMANHATTAN     -453.73897   11.13873 -40.735  < 2e-16 ***\nBoroughQUEENS        -164.57858   14.30008 -11.509  < 2e-16 ***\nBoroughSTATEN ISLAND -770.56770   15.65323 -49.227  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 85.83 on 806 degrees of freedom\n  (88 observations deleted due to missingness)\nMultiple R-squared:  0.9499,\tAdjusted R-squared:  0.9496 \nF-statistic:  3055 on 5 and 806 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(lm_borough)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9543.053\n```\n\n\n:::\n:::\n\n\nThis linear regression model tests the association between monthly residential mold complaints and domestic violence reports within each borough rather than across the city.\n\n-   Strength: very strong (R\\^2 = 0.94)\n\n-   Direction: positive\n\n-   Significance: statistically significant (p\\<0.05)\n\n-   AIC: 10571.03\n\nThe association between mold complaints and DV reports remains positive and statistically significant. Including boroughs greatly increases the R\\^2, showing that much of the variation in DV reports is explained by differences between boroughs rather than mold alone. The borough coefficients compare each borough to the Bronx and highlight that DV reporting levels differ substantially across boroughs.\n\n#### DV \\~ Mold + Borough + Average Resolution Days\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregated_dv_mold_data <- aggregated_dv_mold_data %>%\n  left_join(mold_monthly_resolution, by = c(\"Year\", \"Month\"))\n\nlm_resolution_borough <- lm(\n  `DV Reports` ~ `Mold Complaints` + Borough + avg_resolution_days,\n  data = aggregated_dv_mold_data\n)\n\nsummary(lm_resolution_borough)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = `DV Reports` ~ `Mold Complaints` + Borough + avg_resolution_days, \n    data = aggregated_dv_mold_data)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-257.59  -42.77   -2.31   38.85  376.84 \n\nCoefficients:\n                       Estimate Std. Error t value Pr(>|t|)    \n(Intercept)           993.32749   17.99077  55.213  < 2e-16 ***\n`Mold Complaints`       0.17433    0.01928   9.041  < 2e-16 ***\nBoroughBROOKLYN        59.17692    8.85276   6.685 4.33e-11 ***\nBoroughMANHATTAN     -460.04883   10.94783 -42.022  < 2e-16 ***\nBoroughQUEENS        -177.24615   14.14608 -12.530  < 2e-16 ***\nBoroughSTATEN ISLAND -782.97335   15.45107 -50.674  < 2e-16 ***\navg_resolution_days    -2.88188    0.47425  -6.077 1.89e-09 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 83.98 on 805 degrees of freedom\n  (88 observations deleted due to missingness)\nMultiple R-squared:  0.9521,\tAdjusted R-squared:  0.9517 \nF-statistic:  2665 on 6 and 805 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nAIC(lm_resolution_borough)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9508.634\n```\n\n\n:::\n:::\n\n\nThis linear regression model continues to test the association while incorporating resolution time of mold complaints.\n\n-   Strength: very strong (R\\^2 = 0.95)\n\n-   Direction: negative\n\n-   Significance: statistically significant (p\\<0.05)\n\n-   AIC: 10539.76\n\nEven after controlling for borough and resolution time, mold complaints remain a statistically significant predictor of DV reports. Average resolution days show a statistically significant negative association with DV reports, suggesting that months with longer resolution delays are associated with fewer reported DV incidents. While this may intuitively feel like the opposite of the expected result, this could be due to many factors, such as a lack of borough/community relationship. For instance, this relationship may have been lower in times where city officials took longer to respond to mold complaints. If there was a low borough/community relationship, it is possible community members felt less confident in filing domestic violence reports, out of lack of perceived resources.\n\nOverall, the final linear regression model is our best predictive model for domestic violence reports. With R\\^2 of 0.95, and the lowest AIC out of the three regression models (10539.76), this model best supports the hypothesis that domestic violence reports can be predicted by residential mold complaints in the same area at the same time.\n\n## Discussion & Insights\n\nOverall, the results show a consistent positive association between residential mold complaints and domestic violence reports. Simple correlations suggest that months with more mold complaints tend to have more DV reports as well. This pattern appears at both yearly and monthly levels.\n\nWhen borough differences are accounted for in regression models, the relationship between mold complaints and DV reports still remains statistically significant, but weaker. This suggests that while borough-level differences explain much of the variation, mold complaints still have an independent association with DV reports.\n\nAdding average mold resolution time shows that longer resolution delays are associated with lower DV report counts. This may be due to reporting behavior or service engagement rather than a direct effect.\n\nLagged analyses were used to test whether mold complaints in one month are related to DV reports in the following month. Although the lagged relationship remains positive, it closely resembles the non-lagged results, suggesting that the results may not largely be due to time.\n\nIn summary, the analysis suggests a consistent positive relationship between residential mold complaints and domestic violence reports, but borough-level differences and other contextual factors appear to drive much of the variation, highlighting the complexity of environmental and social influences on public health outcomes. In the future, I would like to look at neighborhood-specific trends, or DV/mold rates instead of counts as populations vary across boroughs.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}