{
  "hash": "1e14bddc753f4572e3f553a1a730bb54",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Beating Around the Bush: Uncovering the Hidden Link Between Urban Trees and Wildlife Activity\"\nauthor: \"Xinru Wang\"\ndescription: \"This project explores how street tree distribution relates to wildlife activity across New York City by combining tree census data with wildlife incident reports. Using borough-level summaries, spatial visualizations, and exploratory statistical analyses, the study examines patterns in urban ecology and highlights how open data can be used to better understand interactions between green infrastructure and wildlife in a complex urban environment.\"\ncategories: [environment, urban-planning]\n---\n\n**Author:** [Xinru Wang](../contributors/xinru-wang.qmd)\n\n## Beating Around the Bush: Uncovering the Hidden Link Between Urban Trees and Wildlife Activity {#sec-xinru}\n\nUrban trees play an important role in shaping city environments. Beyond improving air quality and adding color to city streets, street trees can also provide shelter, food sources, and movement pathways for wildlife living in urban areas. At the same time, cities are fragmented environments where wildlife often comes into contact with human infrastructure, increasing the risk of injury or the need for human intervention.\n\nThe diversity of New York City provides an insightful setting for analyzing these dynamics, as each borough differs in tree coverage, wildlife presence, and urban structure. Some boroughs have more street trees and larger parks, while others are more densely developed. This variation allows for comparisons between tree distribution and reported wildlife incidents across the city.\n\nUsing NYC Open Data from the [2015 NYC Street Tree Census](https://data.cityofnewyork.us/Environment/2015-Street-Tree-Census-Tree-Data/uvpi-gqnh/about_data){target=\"_blank\"} and the [Urban Park Ranger Animal Condition Response](https://data.cityofnewyork.us/Environment/Urban-Park-Ranger-Animal-Condition-Response/fuhs-xmg2/about_data){target=\"_blank\"} dataset, this project explores the relationship between street trees and wildlife incidents across New York City boroughs. Specifically, this analysis asks:\n\n(1) how street trees are distributed across boroughs\n(2) how wildlife incidents vary by borough\n(3) whether borough-level tree characteristics are associated with wildlife incident patterns\n\nThis project uses descriptive and exploratory analyses to examine how urban trees and wildlife activity coexist within a large metropolitan city such as New York City.\n\n## Required Packages\n\nFor this project, I used the following R packages to clean, analyze, and visualize the data.\n\n(@R-tidyverse) (@R-janitor) (@R-skimr) (@R-ggplot2) (@R-knitr) (@R-supernova) (@R-rcompanion) (@R-arrow)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(janitor)\nlibrary(skimr)\nlibrary(ggplot2)\nlibrary(knitr)\nlibrary(supernova)\nlibrary(rcompanion)\nlibrary(arrow)\nlibrary(here)\n```\n:::\n\n\n## Data and Methods \n\n### Data Sources\n\nThis analysis uses two publicly available datasets from NYC Open Data. The first dataset is the `2015 NYC Street Tree Census`, which documents the location and characteristics of street trees across New York City. For this study, the Street Tree Census was used to calculate the total number of street trees in each borough, serving as a borough-level measure of street tree abundance.\n\nThe second dataset is the `Urban Park Ranger Animal Condition Response` dataset, which records requests for wildlife assistance, relocation, and rescue responded to by NYC Park Rangers. This dataset was used to calculate the total number of wildlife-related incidents in each borough, serving as a proxy measure of wildlife activity.\n\nAlthough the two datasets capture different aspects of the urban environment—street trees located primarily along streets and wildlife incidents occurring primarily within park properties—they were analyzed together at the borough level to explore broader spatial patterns in urban ecology across New York City. All analyses were conducted using aggregated borough-level summaries.\n\nI began by downloading publicly available datasets from NYC Open Data and importing them into R as CSV files for data cleaning, analysis, and visualization.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Import NYC Open Data CSV files\ntree_data <- read_parquet(\n  here(\"data\", \"raw\",\"2015_Street_Tree_Census.parquet\"))\nanimal_data <- read_parquet(\n  here(\"data\", \"raw\",\"Urban_Park_Ranger_Animal_Condition_Response.parquet\"))\n```\n:::\n\n\n### Data Cleaning and Preparation\n\nBefore analysis, I cleaned and prepared the data by selecting relevant variables, addressing missing values, and ensuring consistent formatting across datasets.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Standardize column names\ntree_data <- tree_data %>% clean_names()\nanimal_data <- animal_data %>% clean_names()\n\n# Select variables needed for tree-level analysis\ntree_clean <- tree_data %>%\n  select(borough, health, tree_dbh, latitude, longitude)\n\n# Select variables needed for wildlife incident analysis\nanimal_clean <- animal_data %>%\n  select(borough, species_description, animal_class, animal_condition, property)\n\n# Check for missing borough values\nsum(is.na(tree_data$borough))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(animal_data$borough))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n\n```{.r .cell-code}\n# Convert key categorical variables to factors and clean missing values\ntree_clean <- tree_clean %>%\n  mutate(\n    health = factor(health, levels = c(\"Poor\", \"Fair\", \"Good\"))\n  )\n\nanimal_clean <- animal_clean %>%\n  mutate(\n    animal_condition = na_if(animal_condition, \"N/A\"),\n    animal_condition = factor(animal_condition),\n    animal_class = factor(animal_class)\n  )\n```\n:::\n\n\n## Descriptive Analysis (Plots)\n\nTo describe how street trees and wildlife incidents vary across New York City, I summarized the total number of urban trees and reported wildlife incidents in each borough and visualized these counts using a bar chart.\n\n### Street Tree Distribution Across Boroughs (**Bar chart**)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntree_summary <- tree_clean %>%\n  group_by(borough) %>%\n  summarise(\n    total_trees = n(),\n    pct_good_health = mean(health == \"Good\", na.rm = TRUE),\n    avg_dbh = mean(tree_dbh, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nggplot(tree_summary,\n       aes(x = reorder(borough, -total_trees),\n           y = total_trees)) +\n  geom_col(fill = \"chartreuse4\") +\n  labs(\n    title = \"Total Street Trees by Borough\",\n    x = \"Borough\",\n    y = \"Total Street Trees\"\n  ) +\n  theme_minimal(base_size = 12) +\n    theme(plot.title = element_text(size = 17, family = \"serif\", face = \"bold\"),\n        axis.title.x = element_text(size = 12, family = \"serif\"),\n        axis.title.y = element_text(size = 12, family = \"serif\"))\n```\n\n::: {.cell-output-display}\n![Total number of street trees recorded in the 2015 NYC Street Tree Census, summarized by borough.](08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files/figure-html/fig-tree-summary-1.png){#fig-tree-summary fig-alt='Bar chart of total street trees by NYC borough from the 2015 Street Tree Census, with boroughs ordered from highest to lowest tree count.' width=672}\n:::\n:::\n\n\n#### Interpretation\n\nThe bar chart shows the total number of street trees in each New York City borough. **Queens** has the **largest number** of **street trees**, followed by Brooklyn. **Manhattan** has the **fewest** street trees among the five boroughs. Overall, the distribution highlights substantial differences in street tree availability across boroughs, reflecting variation in land area, residential density, and urban structure.\n\n### Wildlife Incidents Across Boroughs (**Bar chart**)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanimal_summary <- animal_clean %>%\n  group_by(borough) %>%\n  summarise(\n    total_incidents = n(),\n    pct_injured = mean(animal_condition == \"Injured\", na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nggplot(animal_summary,\n       aes(x = reorder(borough, -total_incidents),\n           y = total_incidents)) +\n  geom_col(fill = \"salmon4\") +\n  labs(\n    title = \"Wildlife Incidents by Borough\",\n    x = \"Borough\",\n    y = \"Total Incidents\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(size = 17, family = \"serif\", face = \"bold\"),\n        axis.title.x = element_text(size = 12, family = \"serif\"),\n        axis.title.y = element_text(size = 12, family = \"serif\"))\n```\n\n::: {.cell-output-display}\n![Total number of reported wildlife incidents across NYC boroughs.](08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files/figure-html/fig-animal-summary-1.png){#fig-animal-summary fig-alt='Bar chart of total reported wildlife incidents by NYC borough from the Urban Park Ranger Animal Condition Response dataset, with boroughs ordered from highest to lowest incident count.' width=672}\n:::\n:::\n\n\n#### Interpretation\n\nThe bar chart displays the total number of reported wildlife incidents across New York City boroughs. **Manhattan** reports the **highest** number of **incidents**, followed by Queens and Brooklyn. The Bronx and Staten Island report fewer incidents overall. These differences highlight variation in reported wildlife activity across boroughs, which may reflect differences in park usage, population density, and reporting patterns.\n\n### Combining Tree and Wildlife Data at the Borough Level (**Table**)\n\nAfter examining street trees and wildlife incidents separately, I combined the two borough-level summaries to explore how tree abundance and wildlife incidents relate to one another. By merging the tree and wildlife datasets by borough, this analysis allows for direct comparison between the number of street trees and the frequency of reported wildlife incidents across New York City.\n\n\n::: {#tbl-borough-summary .cell}\n\n```{.r .cell-code}\nborough_summary <- left_join(tree_summary, animal_summary, by = \"borough\")\n\nkable(borough_summary, caption = \"Borough-level summary of street tree characteristics and wildlife incident counts across New York City.\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Borough-level summary of street tree characteristics and wildlife incident counts across New York City.\n\n|borough       | total_trees| pct_good_health|   avg_dbh| total_incidents| pct_injured|\n|:-------------|-----------:|---------------:|---------:|---------------:|-----------:|\n|Bronx         |       85203|       0.8264938|  9.693649|            1221|   0.2153846|\n|Brooklyn      |      177293|       0.8142379| 11.738884|            1614|   0.2896552|\n|Manhattan     |       65423|       0.7586141|  8.473641|            1943|   0.2432432|\n|Queens        |      250551|       0.8152487| 12.557870|            1684|   0.2803970|\n|Staten Island |      105318|       0.8149386| 10.492746|            1151|   0.3310680|\n\n\n:::\n:::\n\n\n### Wildlife Incidents Relative to Street Tree Availability (**Standardized bar chart / rate per 10,000 trees**)\n\nTo account for differences in street tree availability across boroughs, wildlife incidents were standardized by tree count and expressed as incidents per 10,000 street trees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nborough_summary <- borough_summary %>%\n  mutate(incidents_per_10k_trees = total_incidents / total_trees * 10000)\n\nggplot(borough_summary,\n       aes(x = borough, y = incidents_per_10k_trees)) +\n  geom_col(fill = \"dodgerblue4\") +\n  labs(\n    title = \"Wildlife Incidents per 10,000 Street Trees by Borough\",\n    x = \"Borough\",\n    y = \"Incidents per 10,000 Street Trees\"\n  ) +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(size = 17, family = \"serif\", face = \"bold\"),\n        axis.title.x = element_text(size = 12, family = \"serif\"),\n        axis.title.y = element_text(size = 12, family = \"serif\"))\n```\n\n::: {.cell-output-display}\n![Number of wildlife incidents per 10,000 street trees in each New York City borough.](08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files/figure-html/fig-incident-per-tree-1.png){#fig-incident-per-tree fig-alt='Bar chart of wildlife incidents per 10,000 street trees for each NYC borough, comparing incident rates standardized by borough tree totals.' width=672}\n:::\n:::\n\n\n#### Interpretation\n\nThe bar chart shows the number of wildlife incidents per 10,000 street trees in each borough. Manhattan has the highest rate of incidents per tree, even though it has fewer street trees overall. In contrast, Queens has the lowest rate of incidents per tree despite having the most street trees. This suggests that **wildlife incidents are more concentrated in boroughs with fewer street trees** and more spread out in boroughs with higher street-tree density.\n\n### Spatial Distribution of Street Trees (**Binned spatial density plot / heatmap**)\n\nIn addition to borough-level summaries, I examined the spatial distribution of street trees across New York City to better understand how trees are physically distributed throughout the city. Mapping tree density provides context for borough-level patterns and highlights areas where street trees are more concentrated or sparse.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tree_clean, aes(x = longitude, y = latitude)) +\n  geom_bin2d(bins = 50) +\n  scale_fill_viridis_c(\n    option = \"plasma\",\n    name = \"Street Tree Density\"\n  ) +\n  coord_fixed() +\n  labs(\n    title = \"Street Tree Density Across New York City\",\n    subtitle = \"Higher values indicate greater concentration of street trees\",\n    x = \"Longitude\",\n    y = \"Latitude\"\n  ) +\n    theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(size = 17, family = \"serif\", face = \"bold\"),\n        axis.title.x = element_text(size = 12, family = \"serif\"),\n        axis.title.y = element_text(size = 12, family = \"serif\"))\n```\n\n::: {.cell-output-display}\n![Spatial density of street trees across New York City. Each grid cell represents the concentration of street trees based on latitude and longitude, with yellow indicating higher tree density.](08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files/figure-html/fig-binned-map-1.png){#fig-binned-map fig-alt='Binned heatmap of street tree locations across NYC using longitude and latitude. Color intensity shows higher versus lower concentrations of trees across the city map.' width=672}\n:::\n:::\n\n\n#### Interpretation\n\nIn this spatial density binned map areas shown in **yellow** represent **higher concentrations** of **street trees**, while areas shown in purple indicate lower tree density. Higher-density regions are visible across much of Queens and Brooklyn, whereas Manhattan and Staten Island display more fragmented patterns with fewer high-density clusters. Overall, this visualization highlights substantial spatial variation in street tree density across the city, reflecting differences in urban form, land use, and available green space.\n\n### Park-Level Patterns in Wildlife Incidents (**Faceted horizontal bar chart**)\n\nTo further explore where wildlife incidents occur within each borough, I examined park-level patterns by identifying the parks with the highest number of reported wildlife incidents. This allows for a more localized view of wildlife activity within urban green spaces.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanimal_clean %>%\n  count(borough, property) %>%\n  slice_max(n, n = 3, by = borough) %>%\n  ggplot(aes(x = reorder(property, n), y = n)) +\n  geom_col(fill = \"springgreen4\") +\n  coord_flip() +\n  facet_wrap(~ borough, scales = \"free_y\") +\n    theme_minimal(base_size = 10) +\n  theme(plot.title = element_text(size = 17, family = \"serif\", face = \"bold\"),\n        axis.title.x = element_text(size = 12, family = \"serif\"),\n        axis.title.y = element_text(size = 12, family = \"serif\")) +\n  labs(\n    title = \"Most Frequent Parks for Wildlife Incidents by Borough\",\n    x = \"Park\",\n    y = \"Incident Count\"\n  )\n```\n\n::: {.cell-output-display}\n![Top three parks with the highest wildlife incident counts in each borough.](08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files/figure-html/fig-top-3-park-incident-1.png){#fig-top-3-park-incident fig-alt='Faceted horizontal bar charts showing the top three park properties with the highest wildlife incident counts in each NYC borough.' width=672}\n:::\n:::\n\n\n#### Interpretation\n\nAcross boroughs, **wildlife incidents** are concentrated in a small number of major parks. Van Cortlandt Park stands out in the Bronx with the highest number of reported wildlife incidents, while **Central Park** shows the **highest counts** in Manhattan. Prospect Park in Brooklyn also exhibits elevated incident levels relative to other parks in the borough. In contrast, parks in Queens and Staten Island show lower incident counts overall. These patterns suggest that larger parks with extensive natural areas may experience more wildlife activity and a greater likelihood of reported human–wildlife interactions.\n\n### Species Involved in Wildlife Incidents (**Faceted horizontal bar chart**)\n\nTo better understand wildlife incident patterns, I examined which animal species are most frequently involved in reported incidents within each borough.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_species <- animal_clean %>%\n  count(borough, species_description) %>%\n  group_by(borough) %>%\n  slice_max(n, n = 5) %>%\n  ungroup()\n\nggplot(top_species,\n       aes(x = reorder(species_description, n), y = n)) +\n  geom_col(fill = \"mistyrose4\") +\n  coord_flip() +\n  facet_wrap(~ borough, scales = \"free_y\") +\n  labs(\n    title = \"Most Common Wildlife Species Involved in Incidents by Borough\",\n    x = \"Species\",\n    y = \"Number of Incidents\"\n  ) +\n    theme_minimal(base_size = 10) +\n  theme(plot.title = element_text(size = 17, family = \"serif\", face = \"bold\"),\n        axis.title.x = element_text(size = 12, family = \"serif\"),\n        axis.title.y = element_text(size = 12, family = \"serif\"))\n```\n\n::: {.cell-output-display}\n![Most common wildlife species involved in reported incidents across NYC boroughs. Bars represent the number of incidents involving each species, with panels shown separately for each borough.](08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files/figure-html/fig-species-1.png){#fig-species fig-alt='Faceted horizontal bar charts showing the five most frequently reported wildlife species in each NYC borough, with bar length representing incident counts.' width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknitr::include_graphics(here(\"images\", \"raccoon.png\"))\n```\n\n::: {.cell-output-display}\n![Two raccoons resting in a tree in Central Park shortly after dusk, illustrating the presence of adaptable urban wildlife in New York City parks. Photo credit: Chris St Lawrence](../images/raccoon.png){fig-alt='Photo of two raccoons resting on a tree branch in a park setting at dusk.' width=480}\n:::\n:::\n\n\n#### Interpretation\n\nAcross all boroughs, **raccoons** are the **most frequently reported species** involved in **wildlife incidents**, suggesting they are a dominant presence in urban park environments throughout New York City. Domestic animals such as dogs and cats also appear consistently across boroughs, reflecting frequent interactions between pets, wildlife, and human-managed spaces. Some borough-specific patterns emerge, including higher involvement of red-tailed hawks in Manhattan and white-tailed deer and snapping turtles in Staten Island, which likely reflects differences in habitat type, park size, and proximity to less-developed natural areas. Overall, these patterns illustrate how urban wildlife incidents vary not only in frequency but also in species composition across boroughs.\n\n## Inferential and Exploratory Analyses\n\nBuilding on the descriptive patterns observed above, I conducted a series of exploratory statistical analyses to examine whether borough-level differences in urban trees and wildlife incidents were associated with measurable differences in tree characteristics or wildlife outcomes. These analyses are intended to complement the descriptive results and explore potential relationships, rather than to establish causal effects.\n\n### Differences in Average Street Tree Size Across Boroughs (**One-way ANOVA**)\n\nTo examine whether street tree characteristics vary across New York City, I tested whether average tree diameter at breast height (DBH) differed by borough. A one-way ANOVA was used to compare mean tree size across the five boroughs, allowing for an assessment of whether tree size distributions are similar or distinct across urban contexts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_tree <- aov(tree_dbh ~ borough, data = tree_clean)\nsummary(aov(tree_dbh ~ borough, data = tree_clean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                Df   Sum Sq Mean Sq F value Pr(>F)    \nborough          4  1241407  310352    4178 <2e-16 ***\nResiduals   683783 50788948      74                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsupernova(anova_tree)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Analysis of Variance Table (Type III SS)\n Model: tree_dbh ~ borough\n\n                                   SS     df         MS        F   PRE     p\n ----- --------------- | ------------ ------ ---------- -------- ----- -----\n Model (error reduced) |  1241407.100      4 310351.775 4178.336 .0239 .0000\n Error (from model)    | 50788948.448 683783     74.276                     \n ----- --------------- | ------------ ------ ---------- -------- ----- -----\n Total (empty model)   | 52030355.548 683787     76.091                     \n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\nA one-way ANOVA revealed a **statistically significant difference in average street tree diameter (DBH) across New York City boroughs**, F(4, 683,783) = 4178.34, p \\< .001. This result indicates that mean tree size varies by borough. However, the associated effect size was small (η² = 0.024), suggesting that borough-level differences account for only a small proportion of the overall variation in tree DBH. While boroughs differ in average tree size, most variability in tree diameter is likely driven by other factors such as species composition, tree age, and local environmental conditions.\n\n### Association Between Borough and Wildlife Condition (**Chi-square test of independence**)\n\nIn addition to overall incident counts, I examined whether the condition of wildlife involved in reported incidents varied by borough. A chi-square test of independence was used to assess whether the distribution of animal conditions (e.g., healthy, injured, deceased) differed across boroughs, which helps identify whether certain boroughs experience different wildlife outcomes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable_boro_ac <- table(animal_clean$borough, animal_clean$animal_condition)\nchisq.test(table_boro_ac)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table_boro_ac\nX-squared = 119.49, df = 16, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\ncramerV(table_boro_ac)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCramer V \n 0.06616 \n```\n\n\n:::\n:::\n\n\n#### Interpretation\n\nA chi-square test of independence indicated a **statistically significant association between borough and wildlife condition**, χ²(12) = 113.65, p \\< .001. This suggests that the distribution of wildlife outcomes (e.g., healthy, injured, unhealthy, DOA) varies across New York City boroughs. However, the strength of this association was small, as indicated by Cramér’s V = 0.075. This implies that while borough-level differences in wildlife condition exist, borough alone explains only a small portion of the variation in wildlife outcomes, and other factors likely play a larger role in shaping wildlife condition across the city.\n\n### Exploratory Relationship Between Street Tree Abundance and Wildlife Incidents (**Simple linear regression**)\n\nBecause this analysis is exploratory and based on a small number of borough-level observations, I first examined the relationship visually using a scatter plot. This allows for an intuitive assessment of whether total street tree abundance appears related to wildlife incident counts.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = total_incidents ~ total_trees, data = borough_summary)\n\nResiduals:\n      1       2       3       4       5 \n-258.91   57.84  479.46   67.18 -345.57 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)  \n(Intercept) 1.409e+03  3.764e+02   3.745   0.0332 *\ntotal_trees 8.280e-04  2.462e-03   0.336   0.7588  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 376 on 3 degrees of freedom\nMultiple R-squared:  0.03633,\tAdjusted R-squared:  -0.2849 \nF-statistic: 0.1131 on 1 and 3 DF,  p-value: 0.7588\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(borough_summary,\n       aes(x = total_trees, y = total_incidents, label = borough)) +\n  geom_point(size = 3) +\n  geom_smooth(method = \"lm\", se = FALSE) +\n  geom_text(vjust = -0.8) +\n  annotate(\n  \"text\",\n  x = 225000,\n  y = 1250,\n  label = paste0(\"R² = \", round(r2, 2)),\n  size = 3.5,\n  family = \"serif\") +\n  labs(\n    title = \"Street Tree Abundance and Wildlife Incidents by Borough\",\n    x = \"Total Street Trees\",\n    y = \"Total Wildlife Incidents\"\n  ) +\n    theme_minimal(base_size = 9) +\n  theme(plot.title = element_text(size = 17, family = \"serif\", face = \"bold\"),\n        axis.title.x = element_text(size = 12, family = \"serif\"),\n        axis.title.y = element_text(size = 12, family = \"serif\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The following aesthetics were dropped during statistical transformation: label.\nℹ This can happen when ggplot fails to infer the correct grouping structure in\n  the data.\nℹ Did you forget to specify a `group` aesthetic or to convert a numerical\n  variable into a factor?\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Scatter plot showing the relationship between total street trees and total reported wildlife incidents across New York City boroughs. Each point represents a borough. No clear linear trend is observed, consistent with the results of the exploratory linear regression.](08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files/figure-html/fig-scatterplot-1.png){#fig-scatterplot fig-alt='Scatter plot with one point per NYC borough showing total street trees on the x-axis and total wildlife incidents on the y-axis, with a fitted linear trend line and borough labels.' width=672}\n:::\n:::\n\n\nFinally, a simple linear regression was used to examine the relationship between total street trees and total wildlife incidents across boroughs, treating this analysis as exploratory given the small number of observational units.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimple_regression <- lm(total_incidents ~ total_trees, data = borough_summary)\nsummary(simple_regression)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = total_incidents ~ total_trees, data = borough_summary)\n\nResiduals:\n      1       2       3       4       5 \n-258.91   57.84  479.46   67.18 -345.57 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)  \n(Intercept) 1.409e+03  3.764e+02   3.745   0.0332 *\ntotal_trees 8.280e-04  2.462e-03   0.336   0.7588  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 376 on 3 degrees of freedom\nMultiple R-squared:  0.03633,\tAdjusted R-squared:  -0.2849 \nF-statistic: 0.1131 on 1 and 3 DF,  p-value: 0.7588\n```\n\n\n:::\n\n```{.r .cell-code}\nr2 <- summary(simple_regression)$r.squared\n```\n:::\n\n\n#### Interpretation\n\nAs shown in the scatter plot, there is **no clear linear relationship** between street tree abundance and wildlife incidents across boroughs. This visual pattern is supported by the regression analysis, which found **no significant association** between **total street trees and total wildlife incidents** (β = 0.00083, p = .76, R² = .04). Boroughs with high tree counts, such as Queens, did not consistently report higher numbers of incidents, while Manhattan exhibited a high incident count despite having fewer street trees. Together, these findings suggest that street tree abundance alone does not explain borough-level variation in wildlife incidents.\n\n## Discussion and Implications\n\n### Conclusion\n\nOverall, this analysis helps show how street trees and wildlife incidents are distributed across New York City and how these patterns differ by borough. The descriptive results highlighted clear differences in tree counts, wildlife incident totals, and the species and park locations most often involved. When wildlife incidents were adjusted based on tree availability, differences across boroughs became even clearer, suggesting that the total number of street trees alone does not explain where incidents happen.\n\nThe exploratory statistical analyses supported this pattern. Although average street tree size differed across boroughs, there was no strong or statistically significant relationship between the total number of street trees and wildlife incidents. Wildlife condition also varied by borough, but the small effect size suggests these differences should be interpreted carefully. Taken together, these findings suggest that wildlife activity in urban environments is influenced by many factors beyond street tree abundance, such as park characteristics, land use, and human activity.\n\n### Audience & Relevance\n\nThese findings are relevant to New Yorkers, urban planners, policymakers, community organizations, and wildlife management agencies interested in how green infrastructure and wildlife interact in dense urban environments. Knowing where wildlife incidents occur most often, and how they relate to tree distribution and park locations, can help support decisions around urban greening, park management, and public education.\n\nFor residents, these findings provide insight into how wildlife interactions vary across neighborhoods. For policymakers and planners, the results underscore the importance of considering ecological context and spatial patterns, rather than relying solely on broad measures such as total tree counts, when designing interventions aimed at improving both human and wildlife well-being in cities.\n\n### Connection to Open Data\n\nThis project was completed using publicly available datasets from NYC Open Data, including the `2015 NYC Street Tree Census` and the `Urban Park Ranger Animal Condition Response` dataset. Access to these open datasets allows students, researchers, and community members to independently explore real-world urban and environmental questions.\n\nBy bringing together multiple open datasets, this analysis shows how open data can be used to examine the relationship between urban trees and wildlife activity. This project shows how publicly accessible data can be used in a transparent and reproducible way to explore environmental questions and connect them to urban planning and policy discussions.\n",
    "supporting": [
      "08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}